print-status: False
api:
    name: TheNewsApi
    extension: yml
    dependency:
        update: False
        list:
            web: [Popen,Path]
            local: []
    list: [globals]
    language: EN-US
    git:
        url: https://github.com/SamuelJansen/
        extension: git

    session:
        secret: ${SESSION_SECRET:default}
    api-key:
        secret: ${API_KEY_SECRET:default}
    security:
        secret: ${SECURITY_SECRET:default}
    server:
        scheme: http
        host: 0.0.0.0
        port: 6067
        base-url: /the-news-api
    scheduler:
        enable: ${ENABLE_SCHEDULER_API:True}
    listener:
        enable: ${ENABLE_LISTENER_API:True}
    emitter:
        enable: ${ENABLE_EMITER_API:True}

email-manager-api:
    base-url: ${EMAIL_MANAGER_API_HOST}/email-manager-api
    api-key: ${QUEUE_MANAGER_API_API_KEY:default}
    default-timeout-in-seconds: 10
    contacts:
        the-news: ${THE_NEWS_EMAIL:email@email}

voice-manager-api:
    base-url: ${VOICE_MANAGER_API_HOST}/voice-manager-api
    api-key: ${VOICE_MANAGER_API_API_KEY:default}
    default-timeout-in-seconds: 10

queue-manager-api:
    base-url: ${QUEUE_MANAGER_API_HOST}/queue-manager-api
    api-key: ${QUEUE_MANAGER_API_API_KEY}
    voice-manager-api:
        create-today-news-voice:
            queue-key: ${CREATE_TODAY_NEWS_VOICE_QUEUE_KEY}
            emitter:
                timeout: 2
        persist-today-news-voice:
            listener:
                timeout: 2

swagger:
    # schemes: [${api.server.scheme}] ###- bug
    # host: ${SWAGGER_HOST:${api.server.host}}:${api.server.port} ###- bug
    info:
        # title: ${api.name} ###- commented to make use of auto title and auto description
        # description: Shift Api
        version: 0.0.1
        terms-of-service: http://swagger.io/terms/
        contact:
            name: Samuel Jansen
            email: samuel.jansenn@gmail.com
        license:
            name: Apache 2.0 / MIT License
            url: http://www.apache.org/licenses/LICENSE-2.0.html

python:
    version: 3.9
